add some doc strings to neural network functions
cog-imperial/OMLT pull request #64
Opened 2022-03-04 14:35 UTC by tsaycal

2022-03-10 09:09 UTC, rmisener requested changes
There seem to be some mistakes in these doc strings. When I run "make html" from the docs directory, I get an error "Misplaced &" in basically all of these newly-added doc strings. The error seems to be in the LaTeX-like code.

Also, I realize this is an error introduced in a different commit, but would you please change "doucmentation" to "documentation" in README.rst (main folder)?

2022-03-11 22:48 UTC, jalving commented
I notice doc strings with LaTeX need to be raw strings (e.g. r"\alpha") or use double backslashes. I fixed the typo in the readme too.

2022-03-14 20:57 UTC, rmisener approved these changes

2022-03-14 20:57 UTC, rmisener commented
Thanks, @tsaycal and @jalving! This is looking great.

2022-03-14 20:58 UTC, merged